baseurl = "sysnu1l.github.io/internetanthology/"
title = "internet anthology"
theme ="hugo-theme-basic"
languageCode = "en-us"
# googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true
copyright = "© 2019" 
description = ""

[taxonomies]
   category = "categories"
   series = "series"
   tag = "tags"

[params]
   titleEmoji = ":floppy_disk:"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
   name = "blog"
   url = "post/"

#[[params.menu]]   
  # name = "post series"
  # url = "series/"

[[params.menu]]
   name = "about"
   url = "about/"

[[params.menu]]
   name = "links"
   url = "links/"

#[[params.menu]]
  # name = "projects"
  # url = "projects/"

[privacy]
   [privacy.googleAnalytics]
      anonymizeIP = true
      respectDoNotTrack = true
      useSessionStorage = true
   [privacy.twitter]
      enableDNT = true
   [privacy.youtube]
      privacyEnhanced = true
